name: Fast OCR Free

on:
  workflow_dispatch:

jobs:
  ocr-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Tesseract + Bengali + Arabic
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr tesseract-ocr-ben tesseract-ocr-ara tesseract-ocr-eng

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Run Fast OCR
        run: python ocr.py

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: full-book-text
          path: full_book_text.txt
